name: assets_example
description: Example app of assets plugin
version: 1.0.0

environment:
  sdk: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  pedantic: ^1.8.0+1
  assets_annotations:
    path: ../assets_annotations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  assets_codegen:
    path: ../assets_codegen/

flutter:
  uses-material-design: true

  assets:
    - assets/
