name: assets_example
description: Example app of assets plugin
version: 1.0.0
author: Mikhail Alpha <alphamikle@gmail.com>
homepage: https://github.com/alphamikle/assets_plugin/tree/master/assets_example

environment:
  sdk: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  pedantic: ^1.8.0+1
  assets_annotations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  assets_codegen: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
