name: assets_codegen
description: Code generator for assets plugin. Using this with assets_annotation package and one of @AstHelp, @IntlHelp annotations. More info at README.md
version: 1.1.2
homepage: https://github.com/alphamikle/assets_plugin/tree/master/assets_codegen

environment:
  sdk: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.2.2
  source_gen: ^0.9.5
  yaml: ^2.2.0
  path: ^1.6.4
  analyzer: ^0.39.5
  dart_style: ^1.3.4
  edit_distance: ^0.4.1
  assets_annotations: ^1.1.1

dev_dependencies:
  build_test: ^1.0.0
  build_runner: ^1.8.1
  test: ^1.9.4