name: assets_annotations
description: Package of annotations for generate code for assets with @AstHelp annotation at now. You should mark your assetHelperClass with this to generate the code
version: 1.0.1
homepage: https://github.com/alphamikle/assets_plugin/tree/master/assets_annotations

environment:
  sdk: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
