name: assets_annotations
description: Package of annotations for generate code for assets with @AstHelp annotation for generate const classes with your assets paths and preload their content and @IntlHelp annotation for generate LocalizationDelegate class
version: 1.1.0
homepage: https://github.com/alphamikle/assets_plugin/tree/master/assets_annotations

environment:
  sdk: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
